import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./Privacidad.module.css";
import SecondFooter from "@/components/SecondFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portal UAQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + styles.body}>
        {children}
        <SecondFooter />
        </body>
    </html>
  );
}
